version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: titan-nats
    command: [ "-js", "-m", "8222" ]
    ports:
      - "4222:4222" # Client
      - "8222:8222" # Monitoring
    networks:
      - titan-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nats-server", "--version" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  titan-network:
    driver: bridge
