[advisories]
ignore = [
    "RUSTSEC-2025-0009", # ring 0.16 panic on overflow (ethers dependency)
    "RUSTSEC-2025-0010", # ring 0.16 unmaintained (ethers dependency)
    "RUSTSEC-2021-0141", # dotenv unmaintained (but works)
    "RUSTSEC-2025-0057", # fxhash unmaintained
    "RUSTSEC-2024-0384", # instant unmaintained
    "RUSTSEC-2024-0436", # paste unmaintained
    "RUSTSEC-2025-0134", # rustls-pemfile unmaintained
]
